### PR TITLE
Update hack.js

### PR DESCRIPTION
**Pull request by moreauadrien**

### CODE REVIEW

**Comment by thiefadjacent** [comment]
dang, just a little too slow on my part :'(

**Comment by TheNerdMan** [comment]
Still using MD5, when will this boy learn smh

**Comment by kunatastic** [comment]
GG

**Comment by Giancarl021** [comment]
Wow, you guys are fast. Nice

**Comment by TheMrCorvy** [comment]
is this a steins;gate reference? XD

'superhacker'

**Comment by Nintron27** [comment]
Didn't even check it was already solved and went straight to the MD5 rainbow tables, was sad when I returned and was confused that the answer was already there. Either way great job!

**Comment by Lettly** [comment]
WoW so fast

**Comment by daggy1234** [comment]
F

**Comment by bpleonardo** [comment]
Nice

**Comment by yishayhaz** [comment]
dang i just finished watching the video and looked up md5 dec :| you fast af

**Comment by A5H1Q** [comment]
Damn so fast

**Comment by Aravin** [comment]
Oh. missed :/

**Comment by indayush** [comment]
Dammit, I saw the video and then went to the challenge. Should have checked the challenge first.

**Comment by AlexDenver** [comment]
Jesus, did you skip the video?
:rocket: that was super quick.

**Comment by g4solio** [comment]
RIP, wanted to watch the video before, thought it might have some insight on the challenge

**Comment by jonaspetraska7** [comment]
> RIP, wanted to watch the video before, thought it might have some insight on the challenge

same 😥

**Comment by megz15** [comment]
28 minutes too late, I just finished watching the video 🥲
congrats on the lifetime pro courses 😄👍‍

**Comment by NathanAdhitya** [comment]
gg

**Comment by HackProAIT** [comment]
superhacker

**Comment by jroboyd** [comment]
Could have made it a sha256 8 letter randomised for a challenge! or longer using dictionary words.

**Comment by FaisalAfroz** [comment]
When you get notified  late  for  the video and arrive to see the challenge already solved.

**Comment by SimeonKuzman** [comment]
I'd love more of these challenges

**Comment by ligmitz** [comment]
Congratulations 🎉

**Comment by Faks** [comment]
woot, well very well done md5 is easy to crack ;).

**Comment by K1ngjulien** [comment]
Dang it. The one time I'm not clicking on the video within 30 seconds there's goodies to have.
For future travelers, take this: https://md5.gromweb.com/
Since md5 is sooooo broken at this point there's lookup tables everywhere on the web.

**Comment by Semmu** [comment]
gg 👏

**Comment by Semmu** [comment]
damn, i also thought you won, but im not sure anymore, since #1 contains the same answer and also it has been merged already, so i guess that one is the officially accepted solution

**Comment by MoElaSec** [comment]
Super vite damn 5 hours only

**Comment by zakaria-bali** [comment]
I got the result in 1 s using this crack website
imageI

**Comment by omgmanu** [comment]
too easy @codediodeio

**Comment by AhmedNourJamalElDin** [comment]
So easy.
Just copy and paste the hash in [this website](https://hashes.com/en/decrypt/hash)

**Review by AhmedNourJamalElDin — APPROVED** [review]

**Comment by Falci** [comment]
> So easy. Just copy and paste the hash in [this website](https://hashes.com/en/decrypt/hash)

Just [Google it](https://www.google.com/search?q=5e7d28e2cfff93edefb2d15abad07ec5)!

**Comment by IngwiePhoenix** [comment]
bruh my internet was dead for two days, I come back and see this lovely little challenge AND....i am too late.

But seing as it was MD5, well, that was my first thought. Just try to throw the hash into a rainbow table and see what happens. xD

Congrats to the winner!

**Comment by shaun-wild** [comment]
Such a boringly simple challenge - even when Fireship mentions that MD5 is super easy to crack in his video. (Well his commenters did)

**Comment by LexNastin** [comment]
lucky 😒
i wasn't fast enough 😕

**Pull request closed without merging**
